export const PRODUCTS = [
  {
    id: "SHOE-001",
    name: "Nike Air Zoom Pegasus",
    sizes: [39, 40, 41, 42, 43],
    colors: ["black", "white", "red"],
    description: "Yengil, kundalik yugurish uchun mo'ljallangan model.",
    img: "/vercel.svg",
    price: 119.99,
    discountPercent: 10,
    stockStatus: "in_stock", // in_stock | out_of_stock | coming_soon
  },
  {
    id: "SHOE-002",
    name: "Adidas Ultraboost 22",
    sizes: [40, 41, 42, 43, 44],
    colors: ["white", "blue"],
    description: "Qulaylik va qaytarilish uchun Boost texnologiyasi.",
    img: "/vercel.svg",
    price: 159.99,
    discountPercent: 15,
    stockStatus: "in_stock",
  },
  {
    id: "SHOE-003",
    name: "Puma Deviate Nitro",
    sizes: [39, 40, 41, 42],
    colors: ["orange", "black"],
    description: "Nitro ko'pigiga ega yuqori samarali yugurish krosi.",
    img: "/vercel.svg",
    price: 139.99,
    discountPercent: 5,
    stockStatus: "coming_soon",
  },
  {
    id: "SHOE-004",
    name: "New Balance 990v5",
    sizes: [40, 41, 42, 43],
    colors: ["gray", "navy"],
    description: "Klassik ko'rinish va maksimal qulaylik.",
    img: "/vercel.svg",
    price: 179.99,
    discountPercent: 0,
    stockStatus: "in_stock",
  },
  {
    id: "SHOE-005",
    name: "Reebok Nano X",
    sizes: [39, 40, 41, 42, 43],
    colors: ["black", "green"],
    description: "Krossfit va zal mashqlari uchun.",
    img: "/vercel.svg",
    price: 129.99,
    discountPercent: 20,
    stockStatus: "out_of_stock",
  },
  {
    id: "SHOE-006",
    name: "Asics Gel-Kayano 29",
    sizes: [40, 41, 42, 43, 44],
    colors: ["blue", "white"],
    description: "Barqarorlik va qo'llab-quvvatlash uchun.",
    img: "/vercel.svg",
    price: 169.99,
    discountPercent: 12,
    stockStatus: "in_stock",
  },
  {
    id: "SHOE-007",
    name: "Nike Air Jordan 1 Mid",
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["red", "black", "white"],
    description: "Klassik basketbol uslubi.",
    img: "/vercel.svg",
    price: 199.99,
    discountPercent: 0,
    stockStatus: "in_stock",
  },
  {
    id: "SHOE-008",
    name: "Converse Chuck Taylor",
    sizes: [38, 39, 40, 41, 42, 43],
    colors: ["white", "black"],
    description: "Abadiy klassika.",
    img: "/vercel.svg",
    price: 79.99,
    discountPercent: 5,
    stockStatus: "in_stock",
  },
  {
    id: "SHOE-009",
    name: "Vans Old Skool",
    sizes: [38, 39, 40, 41, 42],
    colors: ["black", "white"],
    description: "Skate uslubi va kundalik kiyim.",
    img: "/vercel.svg",
    price: 89.99,
    discountPercent: 0,
    stockStatus: "out_of_stock",
  },
  {
    id: "SHOE-010",
    name: "Hoka Clifton 8",
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["blue", "yellow"],
    description: "Juda yengil va yumshoq amortizatsiya.",
    img: "/vercel.svg",
    price: 149.99,
    discountPercent: 8,
    stockStatus: "in_stock",
  },
];


